import pygame.color

TITLE = "Ben's World"
FPS = 60
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600
SCREEN_COLOR = "green"

PLAYER_WIDTH = 60
PLAYER_HEIGHT = 60
PLAYER_MOVE = 5
PLAYER_COLOR = "blue"

ENEMY_WIDTH = 20
ENEMY_HEIGHT = 20
ENEMY_COLOR = "red"
MAX_ENEMIES = 5
